package org.example.sellsight.analytics.infrastructure.persistence.repository;

import org.example.sellsight.analytics.domain.model.AnalyticsEvent;
import org.example.sellsight.analytics.domain.repository.EventRepository;
import org.example.sellsight.analytics.infrastructure.persistence.entity.UserEventJpaEntity;
import org.springframework.stereotype.Component;

import java.util.List;

/**
 * Adapter — implements the EventRepository port using JPA.
 *
 * Mapping is kept inline (no separate mapper class) because the conversion
 * between AnalyticsEvent and UserEventJpaEntity is straightforward and unlikely
 * to diverge. Extract to a dedicated mapper only if it grows complex.
 */
@Component
public class EventRepositoryAdapter implements EventRepository {

    private final EventJpaRepository jpaRepository;

    public EventRepositoryAdapter(EventJpaRepository jpaRepository) {
        this.jpaRepository = jpaRepository;
    }

    @Override
    public void save(AnalyticsEvent event) {
        jpaRepository.save(toJpa(event));
    }

    @Override
    public List<AnalyticsEvent> findByUserId(String userId) {
        return jpaRepository.findByUserId(userId)
                .stream()
                .map(this::toDomain)
                .toList();
    }

    @Override
    public List<AnalyticsEvent> findByProductId(String productId) {
        return jpaRepository.findByProductId(productId)
                .stream()
                .map(this::toDomain)
                .toList();
    }

    // -------------------------------------------------------------------------
    // Private mapping helpers
    // -------------------------------------------------------------------------

    private UserEventJpaEntity toJpa(AnalyticsEvent event) {
        return new UserEventJpaEntity(
                null,                   // id — generated by the database
                event.userId(),
                event.productId(),
                event.eventType(),
                event.sessionId(),
                event.price(),
                event.timestamp()
        );
    }

    private AnalyticsEvent toDomain(UserEventJpaEntity entity) {
        return new AnalyticsEvent(
                entity.getUserId(),
                entity.getProductId(),
                entity.getEventType(),
                entity.getSessionId(),
                entity.getPrice(),
                entity.getTimestamp()
        );
    }
}
