-- V1__baseline.sql
-- Reproduces the schema that Hibernate previously generated via `ddl-auto: update`.
-- From this migration forward, Flyway owns all schema changes. Hibernate is in
-- `validate` mode and must never diverge — any entity change requires a new V{n} file.
--
-- Column names follow Spring Boot's default SpringPhysicalNamingStrategy
-- (camelCase -> snake_case) to stay compatible with existing @Entity mappings.

-- ===========================================================================
-- users
-- ===========================================================================
CREATE TABLE users (
    id              VARCHAR(255)        NOT NULL,
    first_name      VARCHAR(255)        NOT NULL,
    last_name       VARCHAR(255)        NOT NULL,
    email           VARCHAR(255)        NOT NULL,
    password        VARCHAR(255),
    role            VARCHAR(20)         NOT NULL,
    created_at      TIMESTAMP(6)        NOT NULL,
    is_virtual      BOOLEAN             NOT NULL,
    auth_provider   VARCHAR(20)         NOT NULL,
    provider_id     VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uq_users_email UNIQUE (email)
);

-- ===========================================================================
-- products
-- ===========================================================================
CREATE TABLE products (
    id              VARCHAR(255)        NOT NULL,
    name            VARCHAR(255)        NOT NULL,
    description     TEXT,
    price           NUMERIC(12, 2)      NOT NULL,
    category        VARCHAR(255)        NOT NULL,
    seller_id       VARCHAR(255)        NOT NULL,
    image_url       VARCHAR(255),
    active          BOOLEAN             NOT NULL,
    created_at      TIMESTAMP(6)        NOT NULL,
    updated_at      TIMESTAMP(6),
    CONSTRAINT pk_products PRIMARY KEY (id)
);

CREATE INDEX idx_products_seller   ON products (seller_id);
CREATE INDEX idx_products_category ON products (category);
CREATE INDEX idx_products_active   ON products (active);

-- ===========================================================================
-- orders
-- ===========================================================================
CREATE TABLE orders (
    id              VARCHAR(36)         NOT NULL,
    customer_id     VARCHAR(36)         NOT NULL,
    status          VARCHAR(20)         NOT NULL,
    created_at      TIMESTAMP(6)        NOT NULL,
    updated_at      TIMESTAMP(6),
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

CREATE INDEX idx_orders_customer ON orders (customer_id);
CREATE INDEX idx_orders_status   ON orders (status);

-- ===========================================================================
-- order_items
-- ===========================================================================
CREATE TABLE order_items (
    id              BIGINT              GENERATED BY DEFAULT AS IDENTITY,
    product_id      VARCHAR(255)        NOT NULL,
    product_name    VARCHAR(255)        NOT NULL,
    quantity        INTEGER             NOT NULL,
    unit_price      NUMERIC(12, 2)      NOT NULL,
    order_id        VARCHAR(36)         NOT NULL,
    CONSTRAINT pk_order_items PRIMARY KEY (id),
    CONSTRAINT fk_order_items_order
        FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE
);

CREATE INDEX idx_order_items_order   ON order_items (order_id);
CREATE INDEX idx_order_items_product ON order_items (product_id);

-- ===========================================================================
-- inventory
-- ===========================================================================
CREATE TABLE inventory (
    product_id          VARCHAR(255)    NOT NULL,
    quantity            INTEGER         NOT NULL,
    reorder_threshold   INTEGER         NOT NULL,
    CONSTRAINT pk_inventory PRIMARY KEY (product_id)
);

-- ===========================================================================
-- user_events (behavioral analytics — will migrate to Kafka-only later)
-- ===========================================================================
CREATE TABLE user_events (
    id              UUID                NOT NULL,
    user_id         VARCHAR(255)        NOT NULL,
    product_id      VARCHAR(255),
    event_type      VARCHAR(50)         NOT NULL,
    session_id      VARCHAR(255),
    price           NUMERIC(12, 2),
    timestamp       TIMESTAMP(6)        NOT NULL,
    CONSTRAINT pk_user_events PRIMARY KEY (id)
);

CREATE INDEX idx_events_user    ON user_events (user_id);
CREATE INDEX idx_events_product ON user_events (product_id);
