-- V4__catalog_enhancements.sql
-- Expands the catalog context: brands, product images, product variants,
-- pgvector embedding column, rating aggregation, and full-text search.

-- ── New columns on products ─────────────────────────────────
ALTER TABLE products
    ADD COLUMN brand         VARCHAR(255),
    ADD COLUMN embedding     VECTOR(384),
    ADD COLUMN rating_avg    NUMERIC(3, 2)   NOT NULL DEFAULT 0.00,
    ADD COLUMN rating_count  INTEGER          NOT NULL DEFAULT 0,
    ADD COLUMN sold_count    INTEGER          NOT NULL DEFAULT 0,
    ADD COLUMN search_vector TSVECTOR;

-- GIN index for full-text search
CREATE INDEX idx_products_search ON products USING GIN (search_vector);

-- Index for brand filtering
CREATE INDEX idx_products_brand ON products (brand);

-- HNSW index for pgvector cosine similarity (fast ANN lookups)
CREATE INDEX idx_products_embedding ON products USING hnsw (embedding vector_cosine_ops);

-- Keep search_vector in sync with name + description
CREATE OR REPLACE FUNCTION products_search_vector_trigger() RETURNS trigger AS $$
BEGIN
    NEW.search_vector :=
        setweight(to_tsvector('english', COALESCE(NEW.name, '')), 'A') ||
        setweight(to_tsvector('english', COALESCE(NEW.description, '')), 'B') ||
        setweight(to_tsvector('english', COALESCE(NEW.brand, '')), 'B') ||
        setweight(to_tsvector('english', COALESCE(NEW.category, '')), 'C');
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_products_search_vector
    BEFORE INSERT OR UPDATE OF name, description, brand, category
    ON products
    FOR EACH ROW
    EXECUTE FUNCTION products_search_vector_trigger();

-- Back-fill search_vector for existing rows
UPDATE products SET search_vector =
    setweight(to_tsvector('english', COALESCE(name, '')), 'A') ||
    setweight(to_tsvector('english', COALESCE(description, '')), 'B') ||
    setweight(to_tsvector('english', COALESCE(brand, '')), 'B') ||
    setweight(to_tsvector('english', COALESCE(category, '')), 'C');

-- ── Product images ──────────────────────────────────────────
CREATE TABLE product_images (
    id          BIGINT          GENERATED BY DEFAULT AS IDENTITY,
    product_id  VARCHAR(255)    NOT NULL,
    url         VARCHAR(1024)   NOT NULL,
    sort_order  INTEGER         NOT NULL DEFAULT 0,
    CONSTRAINT pk_product_images PRIMARY KEY (id),
    CONSTRAINT fk_product_images_product
        FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE
);

CREATE INDEX idx_product_images_product ON product_images (product_id);

-- ── Product variants (size / color / SKU) ───────────────────
CREATE TABLE product_variants (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY,
    product_id      VARCHAR(255)    NOT NULL,
    sku             VARCHAR(100)    NOT NULL,
    color           VARCHAR(100),
    size            VARCHAR(50),
    price_override  NUMERIC(12, 2),
    stock           INTEGER         NOT NULL DEFAULT 0,
    active          BOOLEAN         NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_product_variants PRIMARY KEY (id),
    CONSTRAINT fk_product_variants_product
        FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE,
    CONSTRAINT uq_product_variants_sku UNIQUE (sku)
);

CREATE INDEX idx_product_variants_product ON product_variants (product_id);
