-- V5__engagement_context.sql
-- Tables for the Engagement bounded context: reviews, wishlists, Q&A,
-- notifications, price-drop and back-in-stock subscriptions.

-- ── Reviews ─────────────────────────────────────────────────
CREATE TABLE reviews (
    id                 UUID            NOT NULL DEFAULT gen_random_uuid(),
    product_id         VARCHAR(255)    NOT NULL,
    customer_id        VARCHAR(255)    NOT NULL,
    rating             SMALLINT        NOT NULL CHECK (rating BETWEEN 1 AND 5),
    title              VARCHAR(200)    NOT NULL,
    body               TEXT,
    verified_purchase   BOOLEAN         NOT NULL DEFAULT FALSE,
    helpful_count      INTEGER         NOT NULL DEFAULT 0,
    created_at         TIMESTAMP(6)    NOT NULL,
    updated_at         TIMESTAMP(6),
    CONSTRAINT pk_reviews PRIMARY KEY (id),
    CONSTRAINT fk_reviews_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE,
    CONSTRAINT fk_reviews_customer FOREIGN KEY (customer_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uq_reviews_product_customer UNIQUE (product_id, customer_id)
);

CREATE INDEX idx_reviews_product ON reviews (product_id);
CREATE INDEX idx_reviews_customer ON reviews (customer_id);
CREATE INDEX idx_reviews_rating ON reviews (rating);

CREATE TABLE review_images (
    id          BIGINT          GENERATED BY DEFAULT AS IDENTITY,
    review_id   UUID            NOT NULL,
    url         VARCHAR(1024)   NOT NULL,
    CONSTRAINT pk_review_images PRIMARY KEY (id),
    CONSTRAINT fk_review_images_review FOREIGN KEY (review_id) REFERENCES reviews (id) ON DELETE CASCADE
);

CREATE TABLE review_votes (
    review_id   UUID            NOT NULL,
    user_id     VARCHAR(255)    NOT NULL,
    helpful     BOOLEAN         NOT NULL,
    created_at  TIMESTAMP(6)    NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_review_votes PRIMARY KEY (review_id, user_id),
    CONSTRAINT fk_review_votes_review FOREIGN KEY (review_id) REFERENCES reviews (id) ON DELETE CASCADE,
    CONSTRAINT fk_review_votes_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- ── Wishlists ───────────────────────────────────────────────
CREATE TABLE wishlists (
    id          UUID            NOT NULL DEFAULT gen_random_uuid(),
    user_id     VARCHAR(255)    NOT NULL,
    name        VARCHAR(100)    NOT NULL DEFAULT 'My Wishlist',
    created_at  TIMESTAMP(6)    NOT NULL,
    CONSTRAINT pk_wishlists PRIMARY KEY (id),
    CONSTRAINT fk_wishlists_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_wishlists_user ON wishlists (user_id);

CREATE TABLE wishlist_items (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY,
    wishlist_id     UUID            NOT NULL,
    product_id      VARCHAR(255)    NOT NULL,
    added_at        TIMESTAMP(6)    NOT NULL,
    CONSTRAINT pk_wishlist_items PRIMARY KEY (id),
    CONSTRAINT fk_wishlist_items_wishlist FOREIGN KEY (wishlist_id) REFERENCES wishlists (id) ON DELETE CASCADE,
    CONSTRAINT fk_wishlist_items_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE,
    CONSTRAINT uq_wishlist_items UNIQUE (wishlist_id, product_id)
);

-- ── Product Q&A ─────────────────────────────────────────────
CREATE TABLE product_questions (
    id          UUID            NOT NULL DEFAULT gen_random_uuid(),
    product_id  VARCHAR(255)    NOT NULL,
    asker_id    VARCHAR(255)    NOT NULL,
    body        TEXT            NOT NULL,
    created_at  TIMESTAMP(6)    NOT NULL,
    CONSTRAINT pk_product_questions PRIMARY KEY (id),
    CONSTRAINT fk_pq_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE,
    CONSTRAINT fk_pq_asker FOREIGN KEY (asker_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_pq_product ON product_questions (product_id);

CREATE TABLE product_answers (
    id              UUID            NOT NULL DEFAULT gen_random_uuid(),
    question_id     UUID            NOT NULL,
    answerer_id     VARCHAR(255)    NOT NULL,
    body            TEXT            NOT NULL,
    created_at      TIMESTAMP(6)    NOT NULL,
    CONSTRAINT pk_product_answers PRIMARY KEY (id),
    CONSTRAINT fk_pa_question FOREIGN KEY (question_id) REFERENCES product_questions (id) ON DELETE CASCADE,
    CONSTRAINT fk_pa_answerer FOREIGN KEY (answerer_id) REFERENCES users (id) ON DELETE CASCADE
);

-- ── Notifications ───────────────────────────────────────────
CREATE TABLE notifications (
    id          UUID            NOT NULL DEFAULT gen_random_uuid(),
    user_id     VARCHAR(255)    NOT NULL,
    type        VARCHAR(50)     NOT NULL,
    title       VARCHAR(200)    NOT NULL,
    body        TEXT,
    data_json   JSONB,
    read        BOOLEAN         NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP(6)    NOT NULL,
    CONSTRAINT pk_notifications PRIMARY KEY (id),
    CONSTRAINT fk_notifications_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_notifications_user ON notifications (user_id);
CREATE INDEX idx_notifications_unread ON notifications (user_id, read) WHERE read = FALSE;

-- ── Subscriptions (price drop + back in stock) ──────────────
CREATE TABLE price_drop_subscriptions (
    user_id       VARCHAR(255)    NOT NULL,
    product_id    VARCHAR(255)    NOT NULL,
    target_price  NUMERIC(12, 2) NOT NULL,
    created_at    TIMESTAMP(6)    NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_price_drop_subs PRIMARY KEY (user_id, product_id),
    CONSTRAINT fk_pds_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_pds_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE
);

CREATE TABLE back_in_stock_subscriptions (
    user_id       VARCHAR(255)    NOT NULL,
    product_id    VARCHAR(255)    NOT NULL,
    created_at    TIMESTAMP(6)    NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_bis_subs PRIMARY KEY (user_id, product_id),
    CONSTRAINT fk_bis_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_bis_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE
);
