-- V6__promotions_context.sql
-- Promotions bounded context: coupons and coupon usage tracking.

CREATE TABLE coupons (
    id          UUID            NOT NULL DEFAULT gen_random_uuid(),
    code        VARCHAR(50)     NOT NULL,
    type        VARCHAR(20)     NOT NULL,  -- PERCENTAGE or FIXED_AMOUNT
    value       NUMERIC(12, 2)  NOT NULL,
    min_order   NUMERIC(12, 2)  NOT NULL DEFAULT 0.00,
    max_uses    INTEGER,                   -- NULL = unlimited
    used_count  INTEGER         NOT NULL DEFAULT 0,
    starts_at   TIMESTAMP(6)    NOT NULL,
    expires_at  TIMESTAMP(6)    NOT NULL,
    active      BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP(6)    NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_coupons PRIMARY KEY (id),
    CONSTRAINT uq_coupons_code UNIQUE (code),
    CONSTRAINT chk_coupon_type CHECK (type IN ('PERCENTAGE', 'FIXED_AMOUNT')),
    CONSTRAINT chk_coupon_value CHECK (value > 0),
    CONSTRAINT chk_coupon_dates CHECK (expires_at > starts_at)
);

CREATE INDEX idx_coupons_code ON coupons (code);
CREATE INDEX idx_coupons_active ON coupons (active, starts_at, expires_at);

CREATE TABLE coupon_usages (
    id          BIGINT          GENERATED BY DEFAULT AS IDENTITY,
    coupon_id   UUID            NOT NULL,
    user_id     VARCHAR(255)    NOT NULL,
    order_id    VARCHAR(36),
    used_at     TIMESTAMP(6)    NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_coupon_usages PRIMARY KEY (id),
    CONSTRAINT fk_cu_coupon FOREIGN KEY (coupon_id) REFERENCES coupons (id) ON DELETE CASCADE,
    CONSTRAINT fk_cu_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_coupon_usages_coupon ON coupon_usages (coupon_id);
CREATE INDEX idx_coupon_usages_user ON coupon_usages (user_id);
