-- V8__commerce_enhancements.sql
-- Enhances Commerce: shipping addresses, DB-backed carts, enriched orders,
-- and refund-request tracking.

-- ── Addresses ───────────────────────────────────────────────
CREATE TABLE addresses (
    id                      UUID            NOT NULL DEFAULT gen_random_uuid(),
    user_id                 VARCHAR(255)    NOT NULL,
    label                   VARCHAR(50)     NOT NULL DEFAULT 'Home',
    first_name              VARCHAR(100)    NOT NULL,
    last_name               VARCHAR(100)    NOT NULL,
    street                  VARCHAR(255)    NOT NULL,
    city                    VARCHAR(100)    NOT NULL,
    state                   VARCHAR(100),
    zip                     VARCHAR(20)     NOT NULL,
    country                 VARCHAR(100)    NOT NULL DEFAULT 'US',
    phone                   VARCHAR(30),
    is_default_shipping     BOOLEAN         NOT NULL DEFAULT FALSE,
    is_default_billing      BOOLEAN         NOT NULL DEFAULT FALSE,
    created_at              TIMESTAMP(6)    NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMP(6),
    CONSTRAINT pk_addresses PRIMARY KEY (id),
    CONSTRAINT fk_addresses_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_addresses_user ON addresses (user_id);

-- ── DB-backed cart ──────────────────────────────────────────
CREATE TABLE carts (
    id          UUID            NOT NULL DEFAULT gen_random_uuid(),
    user_id     VARCHAR(255)    NOT NULL,
    created_at  TIMESTAMP(6)    NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMP(6),
    CONSTRAINT pk_carts PRIMARY KEY (id),
    CONSTRAINT fk_carts_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uq_carts_user UNIQUE (user_id)
);

CREATE TABLE cart_items (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY,
    cart_id         UUID            NOT NULL,
    product_id      VARCHAR(255)    NOT NULL,
    variant_id      BIGINT,
    quantity        INTEGER         NOT NULL DEFAULT 1,
    saved_for_later BOOLEAN         NOT NULL DEFAULT FALSE,
    added_at        TIMESTAMP(6)    NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_cart_items PRIMARY KEY (id),
    CONSTRAINT fk_ci_cart FOREIGN KEY (cart_id) REFERENCES carts (id) ON DELETE CASCADE,
    CONSTRAINT fk_ci_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE,
    CONSTRAINT uq_cart_items UNIQUE (cart_id, product_id, variant_id)
);

CREATE INDEX idx_cart_items_cart ON cart_items (cart_id);

-- ── Order enhancements ──────────────────────────────────────
ALTER TABLE orders
    ADD COLUMN shipping_address_id      UUID,
    ADD COLUMN billing_address_id       UUID,
    ADD COLUMN coupon_id                UUID,
    ADD COLUMN shipping_method          VARCHAR(50),
    ADD COLUMN shipping_cost            NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
    ADD COLUMN subtotal                 NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
    ADD COLUMN discount                 NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
    ADD COLUMN total                    NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
    ADD COLUMN stripe_payment_intent_id VARCHAR(255),
    ADD COLUMN tracking_number          VARCHAR(100);

-- Backfill total from existing order items
UPDATE orders o SET total = COALESCE((
    SELECT SUM(oi.unit_price * oi.quantity) FROM order_items oi WHERE oi.order_id = o.id
), 0.00), subtotal = COALESCE((
    SELECT SUM(oi.unit_price * oi.quantity) FROM order_items oi WHERE oi.order_id = o.id
), 0.00);

-- ── Refund requests ─────────────────────────────────────────
CREATE TABLE refund_requests (
    id              UUID            NOT NULL DEFAULT gen_random_uuid(),
    order_id        VARCHAR(36)     NOT NULL,
    customer_id     VARCHAR(255)    NOT NULL,
    reason          TEXT            NOT NULL,
    status          VARCHAR(20)     NOT NULL DEFAULT 'PENDING',
    created_at      TIMESTAMP(6)    NOT NULL DEFAULT NOW(),
    resolved_at     TIMESTAMP(6),
    CONSTRAINT pk_refund_requests PRIMARY KEY (id),
    CONSTRAINT fk_rr_order FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE,
    CONSTRAINT fk_rr_customer FOREIGN KEY (customer_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT chk_rr_status CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED'))
);

CREATE INDEX idx_refund_requests_order ON refund_requests (order_id);
CREATE INDEX idx_refund_requests_customer ON refund_requests (customer_id);
